export const NOTIFICATIONTYPE = {
    GETALL: {
        FETCH: "NOTIFICATION/GETALL",
        SUCCESS: "NOTIFICATION/GETALL/SUCCESS",
        ERROR: "NOTIFICATION/GETALL/ERROR",
    },
    CREATE: {
        FETCH: "NOTIFICATION/CREATE",
        SUCCESS: "NOTIFICATION/CREATE/SUCCESS",
        ERROR: "NOTIFICATION/CREATE/ERROR",
    },
    UPDATE: {
        FETCH: "NOTIFICATION/UPDATE",
        SUCCESS: "NOTIFICATION/UPDATE/SUCCESS",
        ERROR: "NOTIFICATION/UPDATE/ERROR",
    },
    REMOVE: {
        FETCH: "NOTIFICATION/REMOVE",
        SUCCESS: "NOTIFICATION/REMOVE/SUCCESS",
        ERROR: "NOTIFICATION/REMOVE/ERROR",
    },
    RESET: {
        FETCH: "NOTIFICATION/RESET",
    }
}